# Generated by Django 5.0 on 2024-07-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='blogs',
        ),
    ]
